[hlm-2348]: changed boundary generation logic to pick from boundary persistence table
egovernments/HCM-Mozambique-Implementation pull request #24
Opened 2023-04-04 09:01 UTC by vishal-egov

2023-04-04 12:27 UTC, khushali-egov requested changes

2023-04-04 12:27 UTC, khushali-egov commented on hcm-moz-impl/src/main/java/hcm/moz/impl/service/BoundaryGenerationService.java
> +    public BoundaryData generateBoundaryJson(List<BoundaryPersistence> boundaryPersistenceList) {
Change the name for BoundaryPersistence as DHIS2Boundary similar to DHIS2Record

2023-04-04 12:27 UTC, khushali-egov commented on hcm-moz-impl/src/main/java/hcm/moz/impl/service/BoundaryGenerationService.java
> +    private BoundaryData setBoundaryData(BoundaryPersistence parentBoundary,
We can move this logic to anew method in DHIS2DigitMapper class (mapBoundaryData something like this) and use mapper annotation to map fields from object of BoundaryPersistence to BoundaryData (Rename it as BoundaryMdmsData)

2023-04-04 13:11 UTC, vishal-egov commented on hcm-moz-impl/src/main/java/hcm/moz/impl/service/BoundaryGenerationService.java
> +    private BoundaryData setBoundaryData(BoundaryPersistence parentBoundary,
Since this is not atypical mapping and involves recursion we can keep it here for now

2023-04-04 13:11 UTC, vishal-egov commented on hcm-moz-impl/src/main/java/hcm/moz/impl/service/BoundaryGenerationService.java
> +            if (boundaryPersistenceList != null && !boundaryPersistenceList.isEmpty()) {
Done

2023-04-05 02:29 UTC, khushali-egov approved these changes

2023-04-05 02:29 UTC, merged